### ISSUE TITLE
RemovedConnectionAlerts could not be started.

### ISSUE THREAD

**Issue by toastewoofs** [iyu46/RemovedConnectionAlerts#18]
Whenever starting the plugin. BD version 1.9.6, discord version Stable 247929 (393c680)

RemovedConnectionAlerts v0.7.2 could not be started.

 SyntaxError: Unexpected token '', ""... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.ensurePluginData (renderer.js:5:13864)
    at Object.getPluginData (renderer.js:5:13965)
    at gt.load (renderer.js:5:365412)
    at getSavedData (RemovedConnectionAlerts.plugin.js:392:32)
    at initializeCurrentSavedData (RemovedConnectionAlerts.plugin.js:515:33)
    at Object.start (RemovedConnectionAle…s.plugin.js:1269:13)
    at A.startPlugin (renderer.js:5:35363)
    at A.startAddon (renderer.js:5:35156)
    at A.enableAddon (renderer.js:5:8634)
e.<computed>	@	cae0e97….js:1
stacktrace	@	renderer.js:5
startPlugin	@	renderer.js:5
startAddon	@	renderer.js:5
enableAddon	@	renderer.js:5
toggleAddon	@	renderer.js:5
togglePlugin	@	renderer.js:5
(anonymous)	@	renderer.js:5
(anonymous)	@	renderer.js:5
eN	@	717531d….js:1
eB	@	717531d….js:1
(anonymous)	@	717531d….js:1
re	@	717531d….js:1
rt	@	717531d….js:1
(anonymous)	@	717531d….js:1
sE	@	717531d….js:1
eC	@	717531d….js:1
rs	@	717531d….js:1
tN	@	717531d….js:1
tF	@	717531d….js:1

**Comment by iyu46** [comment]
Copy of https://github.com/iyu46/RemovedConnectionAlerts/issues/14, which is addressed at https://github.com/iyu46/RemovedConnectionAlerts/issues/6#issuecomment-1805244138.
