### ISSUE TITLE
[Bug] RemovedConnectionAlerts 0.8.7 Debug Console Error

### ISSUE THREAD

**Issue by bubblycatbread** [iyu46/RemovedConnectionAlerts#29]
### Addon Name and Version
RemovedConnectionAlerts 0.8.7

### Discord Version
Discord: stable 355624 (8dc6074) Host 1.0.9175 x64 (56716)
BetterDiscord: stable 1.11.0

### Describe the bug
This error shows up on the debug console whenever I leave a server

### To Reproduce
Leave a server -> Error shows up

### Screenshots
![Removed connection alerts](https://github.com/user-attachments/assets/82b487e4-ac32-4fd5-88d5-d010441e8fed)

**Comment by iyu46** [comment]
Does it affect your client experience negatively in any way? For example, does the button disappear or anything?

**Comment by BubblyBreadysi** [comment]
Yes, it crashes my client. I'm not sure about the button

**Comment by iyu46** [comment]
Sorry, holidays have gotten me backed up with work and rest time. That's super weird - if you close Discord and move your RCA history file away from your plugin folder entirely (make a copy or two first), does it still crash when you leave a server? 

If not, would you be comfortable in sending me that file? 

To reapply your history, close Discord again and rename the backup history file of your choosing to the standard `RemovedConnectionAlerts_{your number here}.config.json`.

**Comment by BubblyBreadysi** [comment]
Hi! I have found the issue that is making discord crash. I did this with a new history file and my old one. Basically, it only crashes when I have the plugin GuildAndFriendRemovalAlerts v3.2.1by Metalloriff enabled.

Here is the error I see when I have both plugins enabled and I leave a server. 

```
[2025-01-03 19:10:27.498][CONSOLE:WARN] [RemovedConnectionAlerts] Attempting to re-render button
[2025-01-03 19:10:27.499][CONSOLE:ERROR] [RemovedConnectionAlerts] View does not contain anchorable elements

 Cannot read properties of null (reading 'lastChild')
TypeError: Cannot read properties of null (reading 'lastChild')
    at insertButtonAtLocationWithStyle (betterdiscord://plugins/RemovedConnectionAlerts.plugin.js:1025:29)
    at Object.onSwitch (betterdiscord://plugins/RemovedConnectionAlerts.plugin.js:1385:13)
    at N.onSwitch (betterdiscord/renderer.js:5:31800)
    at a.emit (betterdiscord/renderer.js:5:377017)
    at a.dispatch (betterdiscord/renderer.js:5:21402)
    at betterdiscord/renderer.js:5:21575
[2025-01-03 19:10:40.947][CONSOLE:LOG] [Routing/Utils] transitionTo - Transitioning to /channels/1102970375731691612/1102974265613099079
[2025-01-03 19:10:42.552][CONSOLE:WARN] [RemovedConnectionAlerts] Attempting to re-render button
[2025-01-03 19:10:46.367][CONSOLE:LOG] [Routing/Utils] Replacing route with /channels/@me
[2025-01-03 19:10:46.832][CONSOLE:INFO] [RemovedConnectionAlerts] Found 1 new removed guilds
[2025-01-03 19:10:46.876][CONSOLE:LOG] main()
[2025-01-03 19:10:46.878][CONSOLE:LOG] [GatewaySocket] Dispatched 2 messages in 53.89999985694885ms
[2025-01-03 19:10:46.937][CONSOLE:ERROR] [GatewaySocket] resetSocketOnError during GUILD_DELETE: Cannot read properties of undefined (reading 'map') TypeError: Cannot read properties of undefined (reading 'map')
    at p.getGuilds (https://discord.com/assets/03b5d9a85aab625613da.js:1:694706)
    at eval (betterdiscord://plugins/GuildAndFriendRemovalAlerts.plugin.js:494:59)
    at https://discord.com/assets/web.cbb75fcbc4f1e7a39072.js:12:8672104
    at Set.forEach (<anonymous>)
    at https://discord.com/assets/web.cbb75fcbc4f1e7a39072.js:12:8672093
    at i (https://discord.com/assets/web.cbb75fcbc4f1e7a39072.js:12:8678558)
    at b._dispatch (https://discord.com/assets/web.cbb75fcbc4f1e7a39072.js:12:8672082)
    at https://discord.com/assets/web.cbb75fcbc4f1e7a39072.js:12:8671596
    at f.log (https://discord.com/assets/web.cbb75fcbc4f1e7a39072.js:12:8678693)
    at b._dispatchWithLogging (https://discord.com/assets/web.cbb75fcbc4f1e7a39072.js:12:8671538)
    at b._dispatchWithDevtools (https://discord.com/assets/web.cbb75fcbc4f1e7a39072.js:12:8671114)
    at Object.dispatch_GUILD_DELETE [as GUILD_DELETE] (https://discord.com/assets/web.cbb75fcbc4f1e7a39072.js:12:8670428)
    at https://discord.com/assets/web.cbb75fcbc4f1e7a39072.js:12:8670529
    at b.flushWaitQueue (https://discord.com/assets/web.cbb75fcbc4f1e7a39072.js:12:8671010)
    at https://discord.com/assets/web.cbb75fcbc4f1e7a39072.js:12:8670559
    at new Promise (<anonymous>)
    at b.dispatch (https://discord.com/assets/web.cbb75fcbc4f1e7a39072.js:12:8670308)
    at b.dispatch (betterdiscord/renderer.js:5:24296)
    at W (https://discord.com/assets/web.cbb75fcbc4f1e7a39072.js:12:4977416)
    at Object.dispatch (https://discord.com/assets/web.cbb75fcbc4f1e7a39072.js:12:4987083)
    at N.dispatchOne (https://discord.com/assets/web.cbb75fcbc4f1e7a39072.js:12:4962166)
    at https://discord.com/assets/web.cbb75fcbc4f1e7a39072.js:12:4960828
    at _.batched (https://discord.com/assets/web.cbb75fcbc4f1e7a39072.js:12:8676167)
    at N.dispatchMultiple (https://discord.com/assets/web.cbb75fcbc4f1e7a39072.js:12:4960716)
    at p.<anonymous> (https://discord.com/assets/web.cbb75fcbc4f1e7a39072.js:12:4962837)
    at p._processWorkCallback (https://discord.com/assets/web.cbb75fcbc4f1e7a39072.js:12:4912494)
    at _scheduleRequestIdleCallback.timeout (https://discord.com/assets/web.cbb75fcbc4f1e7a39072.js:12:4918514)
    at https://discord.com/assets/web.cbb75fcbc4f1e7a39072.js:12:4918645 
```
    
    
![image](https://github.com/user-attachments/assets/df2b4309-1359-4d7f-a152-b444958bd6ef)

**Comment by iyu46** [comment]
Why do you have both enabled at the same time? They do the same thing, except mine was written to replace GuildAndFriendRemovalAlerts entirely - that plugin is ancient and hasn't been updated to work with the current version of Discord in years.

**Comment by BubblyBreadysi** [comment]
I forgot to disable the plugin so I just had in run in the background

**Comment by iyu46** [comment]
Okay! My plugin runs fine otherwise?

**Comment by Miniontoby** [comment]
I also have this error, however I don't have `GuildAndFriendRemovalAlerts` installed

```js
[RemovedConnectionAlerts] View does not contain anchorable elements TypeError: Cannot read properties of null (reading 'lastChild')
 at insertButtonAtLocationWithStyle (RemovedConnectionAlerts.plugin.js:1031:29)
 at eval (RemovedConnectionAlerts.plugin.js:1365:25)
 at eval (RemovedConnectionAlerts.plugin.js:997:21)
 at Array.forEach (<anonymous>)
 at MutationObserver.eval (RemovedConnectionAlerts.plugin.js:991:23)
```

Unsure if this is true or not, but it seems like if there's a crash, then it shows this error. 

It seems that `const nitroTopBar = getNitroHeaderContainer();` doesn't give you a value, which would make sense that there isn't any element that matches `document.querySelector(`.${CssClasses.nitroTopBar}`)` when the crash screen is shown...

And yeah, I checked by adding: `if (!nitroTopBar) return` and it no longer shows the error message when discord crashes.
So it's not the fault of this plugin.

However, my advise would be to add some kind of check/statement to NOT show this message if discord crashed, cause it will confuse people and keep reporting the 'error'
