### ISSUE TITLE
An error was encountered while trying to load this plugin.

### ISSUE THREAD

**Issue by Pyddkae** [iyu46/RemovedConnectionAlerts#6]
How do i fix this, it pops up

https://prnt.sc/_ASuwvelEijU

**Comment by iyu46** [comment]
Can you show me any error messages that appear in the console?

**Comment by QuentinMcCarthy** [comment]
SyntaxError: Unexpected token ' ', "                       "... is not valid JSON
at JSON.parse (<anonymous>)
    at Object.ensurePluginData (renderer.js:4:14025)
    at Object.getPluginData (renderer.js:4:14124)
    at Ot.load (renderer.js:4:358386)
    at getSavedData (RemovedConnectionAlerts.plugin.js:332:32)
    at initializeCurrentSavedData (RemovedConnectionAlerts.plugin.js:422:33)
    at Object.start (RemovedConnectionAlerts.plugin.js:900:13)
    at A.startPlugin (renderer.js:4:35582)
    at A.startAddon (renderer.js:4:35375)
    at A.enableAddon (renderer.js:4:8916)
    at A.toggleAddon (renderer.js:4:9173)
    at A.togglePlugin (renderer.js:4:32667)
    at renderer.js:4:85194
    at renderer.js:4:79324
    at Object.Me (5d60241f1a35b792bb74.js:1731:509)
    at je (5d60241f1a35b792bb74.js:1731:663)
    at 5d60241f1a35b792bb74.js:1752:416
    at Ur (5d60241f1a35b792bb74.js:1752:513)
    at Gr (5d60241f1a35b792bb74.js:1752:927)
    at 5d60241f1a35b792bb74.js:1758:415
    at cc (5d60241f1a35b792bb74.js:1823:267)
    at Le (5d60241f1a35b792bb74.js:1730:624)
    at Yr (5d60241f1a35b792bb74.js:1754:232)
    at Kt (5d60241f1a35b792bb74.js:1737:858)
    at Zt (5d60241f1a35b792bb74.js:1737:642)
    at HTMLDivElement.n (c7ba3c7ba97a256b835b.js:237:559)

**Comment by iyu46** [comment]
> Just today

Would you be willing to share your cache file?

**Comment by QuentinMcCarthy** [comment]
Dunno what, or where, that is

**Comment by iyu46** [comment]
> Dunno what, or where, that is

Your history files can be found next to the plugin itself. They are named `RemovedConnectionAlerts_{your Discord user ID number here}.config.json`.

**Comment by QuentinMcCarthy** [comment]
Sorry for the late response, forgot about this I'll admit. I found the file in question, and this is definitely _not_ a JSON as the file type would imply. No JSON I've ever seen is full of nul characters...

GitHub won't let me upload it as a JSON, so...
[RemovedConnectionAlertsCache.zip](https://github.com/iyu46/RemovedConnectionAlerts/files/11331754/RemovedConnectionAlertsCache.zip)
Hopefully that works?

**Comment by dudeedud4** [comment]
I am getting the same error as well now. Also with the .json file full of NUL characters.

**Comment by toastewoofs** [comment]
> Can you show me any error messages that appear in the console?

I also get this issue.
![image](https://github.com/iyu46/RemovedConnectionAlerts/assets/140748595/2bd0385a-58fa-458f-b654-98d107645e98)

**Comment by iyu46** [comment]
To my current understanding, this is caused by an unexpected event to Discord while the plugin is trying to save your data. The most likely event is Discord randomly crashing. I'm not entirely sure that this is the sole type of reason for this issue but it's one that I have no control over.
